=== LewkoM/HobbyWebsite/wedkarstwo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="wedkarstwo" >
		<xs:complexType >
			<xs:sequence>
				<xs:element name="main" type="mainType" />
				<xs:element name="media" type="mediaType" minOccurs="0" maxOccurs="4" />
                <xs:element name="links" type="linksType"  maxOccurs="unbounded"/>
                <xs:element ref="author"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:complexType name="mainType">
        <xs:group ref="m"/>
    </xs:complexType>
    
    <xs:group name="m">
        <xs:sequence>
            <xs:element name="wstep" type="wstepType"/>
            <xs:element ref="topic"/>
            <xs:element name="information" type="informationType"/>
        </xs:sequence>
    </xs:group>

        <xs:simpleType name="wstepType">
            <xs:restriction base="xs:string">
                <xs:minLength value="20"/>
                <xs:maxLength value="70"/>
            </xs:restriction>
        </xs:simpleType>

    <xs:element name="topic">
        <xs:complexType>
		    <xs:sequence>
			    <xs:element name="ryby" type="rybyType" minOccurs="1" maxOccurs="2" />
		    </xs:sequence>
	    </xs:complexType>
    </xs:element>

    <xs:complexType name="rybyType">
		<xs:sequence>
			<xs:element name="typ" type="typType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
        <xs:attribute ref="kind" use="required"/>
    </xs:complexType>

	<xs:complexType name="typType" >
		<xs:sequence>
			<xs:element name="nazwa" type="list" minOccurs="0" maxOccurs="1"  />
			<xs:element name="cechy" type="cechyType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute ref="id" />
	</xs:complexType>

<xs:simpleType name="list">
        <xs:list itemType="krotkiType"/>
    </xs:simpleType>
    

    <xs:complexType name="cechyType">
		<xs:sequence>
			<xs:element name="waga" type="xs:decimal" maxOccurs="1" />
			<xs:element name="dlugosc" type="union" maxOccurs="1" />
            <xs:element name="unikalnosc" type="maxkrotkiType" maxOccurs="1" />
		</xs:sequence>
    </xs:complexType>

    

    <xs:simpleType name="union">
        <xs:union memberTypes="krotkiType ograniczenie"/>
     </xs:simpleType>
    
    <xs:complexType name="informationType">
		<xs:sequence>
			<xs:element name="rodzaje" type="rodzajeType" />
			<xs:element name="history" type="historyType" />
		</xs:sequence>
	</xs:complexType>

    <xs:complexType name="rodzajeType">
		<xs:sequence>
			<xs:element name="sposob" type="sposobType"  maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

    <xs:complexType name="sposobType">
        <xs:sequence>
            <xs:element name="tekst"  maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>

    <xs:complexType name="historyType">
        <xs:sequence>
            <xs:element name="wiedza">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="tekst"/>
                    </xs:sequence>
                    <xs:attribute name="rok" type="xs:long"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="klub">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="tekst"/>
                    </xs:sequence>
                    <xs:attribute name="zalozenie" type="xs:date"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="wiedzaType">
        <xs:sequence>
            <xs:element ref="tekst"/>
        </xs:sequence>
        <xs:attribute name="rok" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="mediaType">
        <xs:sequence>
            <xs:element name="jpg" type="jpgType" minOccurs="3" maxOccurs="5"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="jpgType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="src" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="linksType">
        <xs:sequence>
            <xs:element name="link" type="linkType" minOccurs="3" maxOccurs="5"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="linkType">
         <xs:simpleContent>
             <xs:extension base="xs:string">
                <xs:attribute name="src">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https://.+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="ograniczenie">
        <xs:restriction base="xs:byte">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:attribute name="id" type="xs:byte"/>
    
    <xs:element name="tekst">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="7000"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:simpleType name="maxkrotkiType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10" />
		</xs:restriction>
	</xs:simpleType>

    <xs:simpleType name="krotkiType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="25" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dlugiType">
		<xs:restriction base="xs:string">
             <xs:minLength value="2" />
			<xs:maxLength value="40" />
		</xs:restriction>
	</xs:simpleType>

    <xs:attribute name="kind" type="kindType" />

	<xs:simpleType name="kindType" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="słodkowodne" />
			<xs:enumeration value="słonowodne" />
		</xs:restriction>
	</xs:simpleType>



    <xs:element name="author" type="authorType" />

    <xs:complexType name="authorType">
		<xs:sequence>
			<xs:element name="name" type="krotkiType" />
			<xs:element name="surname" type="krotkiType" />
		</xs:sequence>
	</xs:complexType>
    
</xs:schema>

=== LewkoM/HobbyWebsite/wedkarstwo.xml
<?xml version="1.0" encoding="utf-8"?>
<wedkarstwo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="wedkarstwo.xsd">

	<main>
		<wstep>Wędkarstwo moja pasja</wstep>
		<topic>
			<ryby kind="słodkowodne">
				<typ id="1">	
					<nazwa>Bieługa</nazwa>
					<cechy>
						<waga>1140</waga>
						<dlugosc>4.5</dlugosc>
						<unikalnosc>rzadka</unikalnosc>
					</cechy>
				</typ>
				<typ id="2">	
					<nazwa>Kaługa</nazwa>
					<cechy>
						<waga>1500</waga>
						<dlugosc>6</dlugosc>
						<unikalnosc>rzadka</unikalnosc>
					</cechy>
				</typ>
				<typ id="3">	
					<nazwa>Jesiotr amerykański</nazwa>
					<cechy>
						<waga>800</waga>
						<dlugosc>6</dlugosc>
						<unikalnosc>rzadka</unikalnosc>
					</cechy>
				</typ>
				<typ id="4">	
					<nazwa>Pangaz</nazwa>
					<cechy>
						<waga>300</waga>
						<dlugosc>3</dlugosc>
						<unikalnosc>popularna</unikalnosc>
					</cechy>
				</typ>
				<typ id="5">	
					<nazwa>Arapaima</nazwa>
					<cechy>
						<waga>200</waga>
						<dlugosc>4.5</dlugosc>
						<unikalnosc>popularna</unikalnosc>
					</cechy>
				</typ>
				<typ id="6">	
					<nazwa>Sum europejski</nazwa>
					<cechy>
						<waga>150</waga>
						<dlugosc>3</dlugosc>
						<unikalnosc>popularna</unikalnosc>
					</cechy>
				</typ>
			</ryby>
			<ryby kind="słonowodne">
				<typ id="1">	
					<nazwa>Rekin Wielorybi</nazwa>
					<cechy>
						<waga>15000</waga>
						<dlugosc>12</dlugosc>
						<unikalnosc>rzadka</unikalnosc>
					</cechy>
				</typ>
			</ryby>
		</topic>

		<information>
			<rodzaje>
				<sposob id="1">
					<tekst>
						Wędkarstwo morskie – rodzaj wędkarstwa, w którym poławia się ryby morskie na wędkę z pokładu łodzi, 
						z brzegu plaży lub z nabrzeża portowego. Zazwyczaj, pod tym pojęciem rozumie się wędkarstwo kutrowe,
						 polegające na łowieniu z pokładu łodzi.
					</tekst>
				</sposob>
				
				<sposob id="2">
					<tekst>
						Wędkarstwo muchowe – jeden ze sposobów wędkowania, polegający na poławianiu ryb techniką z wykorzystaniem 
						metod sztucznych na tzw. muszkę. Wędkarz (muszkarz), posługuje się wędką muchową, która jest zaopatrzona w 
						kołowrotek muchowy oraz jeden z trzech rodzajów sznura, specjalnej linki.
					</tekst>
				</sposob>
				
				<sposob id="3">
					<tekst>
						Wędkarstwo podlodowe – rodzaj hobby i sportu, polegający na połowie ryb spod lodu. Praktykowane na
						zamarzniętych akwenach. Zasady połowu w Polsce regulowane są przez Polski Związek Wędkarski, zawarte w
						Regulaminie Amatorskiego Połowu Ryb PZW.
					</tekst>
				</sposob>

				<sposob id="4">
					<tekst>
						Wędkarstwo spinningowe – metoda sportowego i amatorskiego połowu ryb przy użyciu wędki, kołowrotka i sztucznej 
						przynęty polegająca na naprzemiennym zarzucaniu jej i ściąganiu za pomocą wędziska i kołowrotka. Wędkarz może 
						wykonywać także wabiące ruchy wędziskiem tak, aby ruch przynęty jak najbardziej przypominał ruch chorej, przestraszonej
						rybki.	
					</tekst>
				</sposob>
				<sposob id="5">
					<tekst>
						Trolling – metoda połowu ryb drapieżnych polegająca na ciągnięciu wędką przynęty na żyłce lub lince za łodzią. Ruch przynęty
						imituje ruch ryby i prowokuje do ataku. Przez pewien czas metoda była zakazana w Polsce, obecnie dozwolona. Dozwolona też w
						niektórych krajach Skandynawii.
					</tekst>
				</sposob>
			</rodzaje>
			<history>
				<wiedza rok="1989">
					<tekst>
						Dopiero po 1989 r. większe otwarcie na światową literaturę wędkarską (w której profesjonalna nomenklatura tematu była już
						ukształtowana) oraz nastanie wolności wydawniczej spowodowały ogromne, w stosunku do poprzednich lat, zwiększenie nakładów
						i tytułów wydawnictw wędkarskich, nie tylko ogólnoteoretycznych, ale także wszelkiego rodzaju monografii i pozycji zajmujących
						się wieloma szczegółowymi aspektami wędkarstwa. Na tej podstawie ujednoliciły się pojęcia i definicje dotyczące teorii
						wędkowania. Ustaliły się pewne istotne reguły w tym zakresie (chociaż wciąż w części literatury terminy te są stosowane
						zamiennie).
					</tekst>
				</wiedza>
				<klub zalozenie="1879-07-13">
					<tekst>
						Po wprowadzeniu na terenie Galicji i Lodomerii przepisów ustawy rybackiej indywidualne uprawianie wędkarstwa
						stało się utrudnione, głównie z powodu ustanowienia rewirów rybackich, dzierżawionych przez rozmaitych
						użytkowników. 13 lipca 1879 roku zostało powołane Krajowe Towarzystwo Rybackie, którego pierwszym prezesem
						został dr M. Nowicki, sprawujący funkcję do 30 października 1890 roku. 
					</tekst>
				</klub>
			</history>
		</information>
	</main>

	<media>
		<jpg src="zdj/choch.jpg">photo1</jpg>
		<jpg src="zdj/dwuust.jpg">photo2</jpg>
		<jpg src="zdj/geb.jpg">photo3</jpg>
		<jpg src="zdj/top.jpg">photo4</jpg>
	</media>

	<links>
		<link src="https://pl.wikipedia.org/wiki/W%C4%99dkarstwo">Ogolna wiedza</link>
		<link src="https://dinoanimals.pl/zwierzeta/najwieksze-ryby-slodkowodne-top-10/">Ryby</link>
		<link src="https://blog.decathlon.pl/sport/wedkarstwo/metoda-na-krotkie-wedkarskie-wypady-i-nie-tylko-2/">Metody</link>
		<link src="https://wedkuje.pl/n/drgajaca-szczytowka/2588">picker-info</link>
	</links>

	<author>
		<name>Michal</name>
		<surname>Lewko</surname>
	</author>
</wedkarstwo>
